### ISSUE TITLE
How to interpolate patch embedding layer when size mismatced

### ISSUE THREAD

**Issue by Mountchicken** [facebookresearch/long_seq_mae#2]
Hi authors！
Thanks for the great work. In section 4.1 of the paper, you mentioned that when the patch size at finetune is inconsistent with that during pre-training, the parameters of the patch embedding will be interpolated. Is there a detailed code implementation?
<img width="561" alt="截屏2023-01-07 16 01 26" src="https://user-images.githubusercontent.com/65173622/211140501-3cb567e5-ff87-4e40-9e1e-1db2025bfaf1.png">

**Comment by ronghanghu** [comment]
Hi, we follow the implementation in the [ViTDet paper](https://arxiv.org/abs/2203.16527) to implement the patch embedding. The following is a simple snippet to interpolate the ViT Patch Embed weights (`patch_embed.proj.weight`) to a new patch size of $p=16$:

```python3
import torch.nn.functional as F

new_patch_size = 16
state_dict["patch_embed.proj.weight"] = F.interpolate(
    state_dict["patch_embed.proj.weight"],
    size=(new_patch_size, new_patch_size),
    mode="bicubic",
    align_corners=False,
)
````

**Comment by Mountchicken** [comment]
Thanks for the reply
